auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: yiltoncent.com
url: http://yiltoncent.com
feed: /atom.xml
author_info: <a href="http://yiltoncent.com/">Yiltoncent</a>
